name: Upload Python Package to Fury

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build package
        run: python setup.py sdist
      - name: Upload package to Fury using curl
        run: |
            PACKAGE_FILE=$(ls dist/*.gz | head -n 1)
            curl -F package=@$PACKAGE_FILE https://$FURY_TOKEN@push.fury.io/miroljubmihailovic98/
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}

  create-release:
    runs-on: ubuntu-latest
    needs: deploy

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project (or ensure dist is populated)
        run: |
          # Commands to build or package your project
          echo "Ensure dist directory is populated with release files"

      - name: Check dist directory
        run: ls -la ./dist

      - name: Create a new GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
