name: Upload Python Package to GitHub Packages

on:
  release:
    types: [published]  # Trigger workflow on release creation

permissions:
  contents: read  # Allow reading the repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Checkout the repository
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.x'  # Set Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine  # Install build and twine
    - name: Build package
      run: python -m build  # Build the package (creates dist/ folder)
    - name: Publish package to GitHub Packages
      run: |
        twine upload --repository-url https://upload.github.com/OWNER/REPO dist/*
      env:
        TWINE_USERNAME: ${{ github.actor }}  # GitHub username
        TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}  # GitHub token (automatically available)

  create-release:
    runs-on: ubuntu-latest
    needs: deploy  # Ensure the deploy job runs first

    steps:
    - name: Create a new GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/*  # Attach all files from dist/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
