name: Upload Python Package to Fury

on:
  release:
    types: [published]  # Trigger workflow on release creation

permissions:
  contents: read  # Allow reading the repository contents

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Checkout the repository
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.x'  # Set Python version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build package
        run: python setup.py sdist bdist_wheel  # Build the source distribution and wheel
      - name: Upload package to Fury using curl
        run: |
          curl -F package=@dist/*.tar.gz https://$FURY_TOKEN@push.fury.io/miroljubmihailovic98/
        env:
          FURY_TOKEN: ${{ secrets.FURY_TOKEN }}  # Use a secret to securely store your Fury push token

  create-release:
    runs-on: ubuntu-latest
    needs: deploy  # Ensure the deploy job runs first

    steps:
      - name: Create a new GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: ./dist/*  # Attach all files from dist/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
